spring.application.name=Task-management
server.port=8010

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/taskManagement
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Keycloak
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=task-management
keycloak.resource=task-api
keycloak.credentials.secret=hj1AFkLmmucLZtsDmauuiDH85gM4HPW7
keycloak.public-client=false
keycloak.security-constraints[0].authRoles[0]=admin
keycloak.security-constraints[0].authRoles[1]=user
keycloak.security-constraints[0].securityCollections[0].patterns[0]=/api/*

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/task-management/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/task-management
